### ISSUE TITLE
How to make puppeteer work with agenda.js

### ISSUE THREAD

**Issue by KiariaQAQ** [gs-asrivastav/screenshots-exporter#3]
Such as create a job that use puppeteer to get the site  screenshot every 1 minutes.

It is possible to give an example code? 😁

**Comment by gs-asrivastav** [comment]
@KiariaQAQ well, this project works as a rest api so to integrate with agenda.js you can create a task in your project to call the API and get the image. 
I haven't integrated any schedulers or workers in the project as of now.

**Comment by KiariaQAQ** [comment]
thank you for your reply

**Comment by gs-asrivastav** [comment]
@KiariaQAQ Let me know if it works out for you, otherwise we can collaborate and build the agenda.js side as well.

**Comment by KiariaQAQ** [comment]
yep, it works for me 😁

**Comment by gs-asrivastav** [comment]
Awesome, Good Luck!
